db.jdbcUrl=jdbc:mysql://localhost:3306/newpix?useSSL=false
db.user=root
db.password=
db.driverClassName=com.mysql.cj.jdbc.Driver
db.pool.maximumPoolSize=10
db.pool.minimumIdle=5
db.pool.connectionTimeout=30000